# Generated by Django 3.2.16 on 2024-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240829_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subcribed',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Это имя пользователя уже занято.'}, max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
